In [1]:
lst  = [1,2,3]

In [2]:
import numpy as np

In [4]:
arr  = np.array(lst)

In [5]:
arr

array([1, 2, 3])

In [6]:
my_mat = ([1,2,3],[4,5,6],[7,8,9])

In [7]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [12]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [13]:
np.zeros(3)

array([0., 0., 0.])

In [15]:
np.zeros((2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [19]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [24]:
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [25]:
#identity matrix

In [26]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [28]:
np.random.rand(5)

array([0.08783594, 0.37698504, 0.62269118, 0.17844269, 0.10606295])

In [30]:
np.random.rand(5,5)

array([[0.30004804, 0.99730052, 0.68978131, 0.51167188, 0.92109535],
       [0.72235235, 0.05049627, 0.77281027, 0.63861216, 0.69505612],
       [0.25243112, 0.26093381, 0.85725773, 0.01535301, 0.9963044 ],
       [0.20221026, 0.37346245, 0.77524903, 0.61583732, 0.29743153],
       [0.10801176, 0.2567955 , 0.08339025, 0.02290423, 0.13215845]])

In [33]:
np.random.randn(2,4)

array([[-0.15826195, -0.06437397, -0.95670367,  0.84589051],
       [-0.57287981,  0.21002404,  0.86843718, -1.26326607]])

In [35]:
np.random.randint(1,100,10)

array([44,  5, 26, 91, 66, 32, 21, 22, 61, 23])

In [36]:
arr = np.arange(25)

In [37]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [38]:
ranarr = np.random.randint(0,50,10)

In [39]:
ranarr

array([31, 18, 10, 25, 25,  5, 17, 39, 31, 19])

In [44]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [47]:
ranarr.min()

5

In [48]:
ranarr.max()

39

In [49]:
ranarr.argmax()

7

In [50]:
ranarr.argmin()

5

In [51]:
arr.shape

(25,)

In [55]:
arr = arr.reshape(5,5)

In [56]:
arr.shape

(5, 5)

In [57]:
arr.dtype

dtype('int32')

In [58]:
from numpy.random import randint

In [59]:
randint(2,10)

7