NUMPY INDEXING AND SELECTION

In [1]:
import numpy as np 

In [3]:
arr = np.arange(0,11)

In [4]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [6]:
arr[8]

8

In [9]:
arr[0:3:2]

array([0, 2])

In [10]:
arr[::]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [11]:
arr[::-1]

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

In [12]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [13]:
slice_of_arr = arr[:6]

In [14]:
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [16]:
slice_of_arr[:] = 99

In [17]:
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [18]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [19]:
arr_copy = arr.copy()

In [20]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [22]:
arr_copy[:] = 1

In [23]:
arr_copy

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [24]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [26]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [27]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [38]:
arr_2d[2,2]

45

In [39]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [40]:
arr = np.arange(1,11)

In [41]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [43]:
bool_arr = arr > 5

In [44]:
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [45]:
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

In [46]:
arr[arr<3]

array([1, 2])

In [48]:
arr_2d = np.arange(50).reshape(5,10)

In [52]:
arr_2d[1:3,3:5]

array([[13, 14],
       [23, 24]])